@startuml
title TP2 Simulation System

class Particle {
  +double x
  +double y
  +double r
  +double theta
}

class FlockingParams {
  +double L
  +double rc
  +double v
  +double eta
  +int M
}

class CimStats {
  +double build_seconds
  +double sweep_seconds
  +size_t grid_bytes
  +size_t grid_live_blocks
  +size_t pair_tests
}

class CellGrid {
  -double L_
  -int M_
  -vector< vector<int> > cells_
  +CellGrid(double L, int M, int n = 0)
  +int side() const
  +int cell_count() const
  +double cell_size() const
  +int cell_coord(double v) const
  +int cell_index(int cx, int cy) const
  +void insert(int id, double x, double y)
  +const vector<int>& cell(int index) const
  +void clear()
  +size_t memory_bytes() const
  +size_t live_blocks() const
}

class LinkedCellGrid {
  -double L_
  -int M_
  -vector<int> head_
  -vector<int> next_
  +LinkedCellGrid(double L, int M, int n)
  +int side() const
  +int cell_count() const
  +double cell_size() const
  +int cell_coord(double v) const
  +int cell_index(int cx, int cy) const
  +void insert(int id, double x, double y)
  +Chain cell(int index) const
  +void clear()
  +size_t memory_bytes() const
  +size_t live_blocks() const
}

class Iterator {
  -int id_
  -const vector<int>* next_
  +Iterator()
  +int operator*() const
  +Iterator& operator++()
  +bool operator==(const Iterator&) const
  +bool operator!=(const Iterator&) const
}

class Chain {
  -int first_
  -const vector<int>* next_
  +Chain(int first, const vector<int>& next)
  +Iterator begin() const
  +Iterator end() const
  +bool empty() const
}

class NeighborLists {
  <<type alias>>
  vector< vector<int> >
}

class Cluster {
  <<type alias>>
  vector<int>
}

class Clusters {
  <<type alias>>
  vector<Cluster>
}

class FlockingModule {
  +init_flocking(vector<Particle>&, double L, mt19937& rng)
  +step_vicsek(vector<Particle>&, const FlockingParams&, mt19937&, CimStats*)
  +step_voter(vector<Particle>&, const FlockingParams&, mt19937&, CimStats*)
  +double polarization_va(const vector<Particle>&)
}

class NeighborModule {
  +int cim_max_grid_side(double L, double rc, double r_max)
  +double max_radius(const vector<Particle>&)
  +NeighborLists brute_force_neighbors(...)
  +NeighborLists cim_neighbors(...)
  +NeighborLists cim_linked_neighbors(...)
  +CimStats cim_untimed_stats(...)
}

class ClusterModule {
  +Clusters find_clusters(const NeighborLists&)
  +double cluster_observable_s(const Clusters&)
}

class OffLatticeMain {
  +main(int argc, char* argv[])
}

class ClusterMain {
  +main(int argc, char* argv[])
}

Particle --> FlockingModule
FlockingParams --> FlockingModule

NeighborModule --> CellGrid
NeighborModule --> LinkedCellGrid
NeighborModule --> CimStats
NeighborModule --> NeighborLists
LinkedCellGrid --> Chain
Chain --> Iterator

NeighborLists --> ClusterModule
ClusterModule --> Clusters
Clusters --> Cluster

OffLatticeMain --> FlockingModule
OffLatticeMain --> NeighborModule
OffLatticeMain --> ClusterModule

ClusterMain --> NeighborModule
ClusterMain --> ClusterModule

@enduml